# [SWP391_SE1629]

In [ ]:
USE [master]
GO

In [ ]:
/****** Object:  Database [SWP391_SE1629]    Script Date: 23/02/2023 9:38:17 PM ******/
CREATE DATABASE [SWP391_SE1629]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SWP391_SE1629', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SWP391_SE1629.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SWP391_SE1629_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SWP391_SE1629_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [SWP391_SE1629] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SWP391_SE1629].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SWP391_SE1629] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SWP391_SE1629] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SWP391_SE1629] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SWP391_SE1629] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SWP391_SE1629] SET ARITHABORT OFF 
GO
ALTER DATABASE [SWP391_SE1629] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SWP391_SE1629] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SWP391_SE1629] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SWP391_SE1629] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SWP391_SE1629] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SWP391_SE1629] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SWP391_SE1629] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SWP391_SE1629] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SWP391_SE1629] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SWP391_SE1629] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SWP391_SE1629] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SWP391_SE1629] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SWP391_SE1629] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SWP391_SE1629] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SWP391_SE1629] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SWP391_SE1629] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SWP391_SE1629] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SWP391_SE1629] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SWP391_SE1629] SET  MULTI_USER 
GO
ALTER DATABASE [SWP391_SE1629] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SWP391_SE1629] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SWP391_SE1629] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SWP391_SE1629] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SWP391_SE1629] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SWP391_SE1629] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [SWP391_SE1629] SET QUERY_STORE = OFF
GO

# [dbo].[Accounts]

In [ ]:
USE [SWP391_SE1629]
GO

In [ ]:
/****** Object:  Table [dbo].[Accounts]    Script Date: 23/02/2023 9:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Accounts](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[usename] [nvarchar](50) NULL,
	[password] [nvarchar](100) NULL,
	[email] [nvarchar](100) NULL,
	[role] [int] NULL,
 CONSTRAINT [PK_Accounts] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Debit]

In [ ]:
/****** Object:  Table [dbo].[Debit]    Script Date: 23/02/2023 9:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Debit](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](50) NOT NULL,
	[address] [nvarchar](100) NULL,
	[phone] [int] NULL,
	[email] [nvarchar](100) NULL,
	[total] [int] NOT NULL,
	[crday] [datetime] NOT NULL,
	[uday] [datetime] NOT NULL,
 CONSTRAINT [PK_Debit] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Accounts]

In [ ]:
SET IDENTITY_INSERT [dbo].[Accounts] ON 
INSERT [dbo].[Accounts] ([id], [usename], [password], [email], [role]) VALUES (1, N'bao', N'123456', N'bao@gmail.com', 1)
INSERT [dbo].[Accounts] ([id], [usename], [password], [email], [role]) VALUES (2, N'manh', N'1234', N'manh@gmail.com', 1)
INSERT [dbo].[Accounts] ([id], [usename], [password], [email], [role]) VALUES (3, N'son', N'231', N'son@gmail.com', 2)
INSERT [dbo].[Accounts] ([id], [usename], [password], [email], [role]) VALUES (4, N'manhngu', N'123', N'manhngu@gmail.com', 2)
INSERT [dbo].[Accounts] ([id], [usename], [password], [email], [role]) VALUES (5, N'admin', N'admin', N'hn232324@gmail.com', 2)
SET IDENTITY_INSERT [dbo].[Accounts] OFF
GO

# [dbo].[Debit]

In [ ]:
SET IDENTITY_INSERT [dbo].[Debit] ON 
INSERT [dbo].[Debit] ([id], [name], [address], [phone], [email], [total], [crday], [uday]) VALUES (1, N'Manh', N'Ha Noi', 12345678, N'manh@gmail.com', 0, CAST(N'2023-02-11T13:23:44.000' AS DateTime), CAST(N'2023-02-11T13:23:44.000' AS DateTime))
INSERT [dbo].[Debit] ([id], [name], [address], [phone], [email], [total], [crday], [uday]) VALUES (2, N'Duy', N'Ha Noi', 12345278, N'duy@gmail.com', 0, CAST(N'2023-02-11T13:23:44.000' AS DateTime), CAST(N'2023-02-11T13:23:44.000' AS DateTime))
INSERT [dbo].[Debit] ([id], [name], [address], [phone], [email], [total], [crday], [uday]) VALUES (3, N'Ha', N'Vinh', 12145678, N'ha@gmail.com', 0, CAST(N'2023-02-11T13:23:44.000' AS DateTime), CAST(N'2023-02-11T13:23:44.000' AS DateTime))
INSERT [dbo].[Debit] ([id], [name], [address], [phone], [email], [total], [crday], [uday]) VALUES (4, N'Hong', N'DakLak', 14536678, N'hong@gmail.com', 0, CAST(N'2023-02-11T13:23:44.000' AS DateTime), CAST(N'2023-02-11T13:23:44.000' AS DateTime))
SET IDENTITY_INSERT [dbo].[Debit] OFF
GO

# [SWP391_SE1629]

In [ ]:
USE [master]
GO

In [ ]:
ALTER DATABASE [SWP391_SE1629] SET  READ_WRITE 
GO